baseURL: https://lrg.io/
title: "LRG.io"
theme: 2018
enableEmoji: true
footnoteReturnLinkContents: ↩
LanguageCode: "en-gb"
params:
  AuthorName: "Leigh Garland"
  Description: "Product management, web development, art, architecture and music. All from the mind of LRG - the founder of Studio Zero"
  GitHubUser: toychicken
  TwitterUser: "@extraLRG"
  images:
  - "/assets/profile@600x600.gif"