baseURL: https://lrg.io/
title: "LRG.io"
theme: 2018
enableEmoji: true
footnoteReturnLinkContents: ↩
LanguageCode: "en-gb"
params:
  AuthorName: "Leigh Garland"
  Description: "A product wrangler's thoughts."
  GitHubUser: toychicken
