baseURL: https://lrg.io/
title: "Studio Zero"
theme: 2018
enableEmoji: true
footnoteReturnLinkContents: ↩
LanguageCode: "en-gb"
params:
  AuthorName: "Studio Zero"
  Description: "A boutique product development studio, specialising in customer-experience driven propositions for retail, finance, banking, travel and food"
  GitHubUser: toychicken
