baseURL: https://lrg.io/
title: "lrg.io"
theme: 2023
Author:
  name: "Leigh Garland"
  nick: "ToyChicken"
  email: "leigh@toychicken.co.uk"
enableEmoji: true
LanguageCode: "en-gb"
params:
  Description: "Stuff I make"
  GitHubUser: toychicken
  TwitterUser: "@extraLRG"
  profileImg: "/images/profile.png"
  logoSmall: "/images/lrg_logo@60h.png"
  images:
  - "/assets/profile@600x600.gif"
  section:
    hero:
      johnny: "SUPERMAN!"
    tees:
      teelist: ["MAN"]